# Generated by Django 5.2.4 on 2025-07-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redactors",
                to="news.department",
            ),
        ),
        migrations.AddField(
            model_name="redactor",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this redactor belongs to.",
                related_name="redactor_groups",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="redactor",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this redactor.",
                related_name="redactor_permissions",
                to="auth.permission",
            ),
        ),
    ]
