# Generated by Django 5.2.4 on 2025-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Years of experience in journalism"
            ),
        ),
    ]
